description: >
  Simple Docker based Terraform executor.

docker:
  - image: '<< parameters.image >>'

parameters:
  image:
    description: Specify Docker image for executor
    type: string
    default: hashicorp/terraform:1.0.0 # update commands/install when updating this
