description: >
  Official Hashicorp Terraform docker container.

docker:
  - image: hashicorp/terraform:<<parameters.tag>>

parameters:
  tag:
    description: Specify the hashicorp/terraform docker tag to use.
    type: string
    default: "0.15.0"
