description: >
  Simple Docker based Terraform executor.

docker:
  - image: '<< parameters.image >>'

parameters:
  image:
    description: Specify Docker image for executor
    type: string
    default: hashicorp/terraform:0.14.10
