description: >
  Simple Docker based Terraform executor.

docker:
  - image: '<< parameters.image >>'

resource_class: '<< parameters.resource-class >>'

parameters:
  image:
    description: Specify Docker image for executor
    type: string
    default: hashicorp/terraform:0.14.11 # update commands/install when updating this
  resource-class:
    description: Specify resource class for executor
    type: string
    default: small
