version: 2.1

orbs:
  terraform: circleci/terraform@dev:alpha

jobs:
  single-job-lifecycle:
    executor: terraform/default
    working_directory: "~/src"
    steps:
      - checkout
      - terraform/init:
          path: "."
      - terraform/validate:
          path: "."
      - terraform/fmt:
          path: "."
      - terraform/plan:
          path: "."
      - terraform/apply:
          path: "."
      - terraform/destroy:
          path: "."

workflows:
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          checkout: true
          context: terraform
      - terraform/validate:
          checkout: true
          context: terraform
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          persist-workspace: true
          context: terraform
          requires:
            - terraform/validate
      - terraform/apply:
          attach-workspace: true
          context: terraform
          requires:
            - terraform/plan
          filters:
            branches:
              only: master
